config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  resources :posts, only: [:index,:edit,:new,:create,:update,:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all.order(id: "DESC")
    @page = @posts.page(params[:page]).per(10) #ページネーション
  end
  
  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.save
    redirect_to posts_path
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
      redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:name, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p><%= link_to "投稿ページ", new_post_path %>/<%= link_to "投稿一覧", posts_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PpftestTamaki</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>投稿編集</h1>

<%= form_with model: @post do |f| %>

  <h4>タイトル</h4>
  <%= f.text_field :name %>

  <h4>本文</h4>
  <%= f.text_area :body %>

  <%= f.submit '保存' %>

<% end 

app/views/posts/index.html.erb
<h1>投稿一覧</h1>

<% @posts.each do |post| %>
  
  <div>
    <p><%= post.name %>/<%= post.created_at %></p>
    <p><%= post. body %></p>
    <%= link_to 'Edit', edit_post_path(post.id), class: "btn btn-sm btn-success" %></td>
    <%= link_to 'Destroy', post_path(post.id), method: :delete, "data-confirm" => "本当に消しますか？" , class: "btn btn-sm btn-danger" %>
  </div>

<% end %>

<%= paginate @page %>

app/views/posts/new.html.erb
<h1>投稿ページ</h1>

<%= form_with model: @post,url: posts_path, local: true do |f| %>

  <div>
    <label>投稿者</label><%= f.text_field :name %>
  </div>
  
  <div>
    <label>本文</label><%= f.text_area :body %>
  </div>
  
  <%= f.submit '投稿' %>

<% end %>